In [ ]:
import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import json # library to handle JSON files

!conda install -c conda-forge geopy --yes 
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

#!conda install -c conda-forge folium=0.5.0 --yes # uncomment this line if you haven't completed the Foursquare API lab
import folium # map rendering library

print('Libraries imported.')

In [24]:
url='https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

table = pd.read_html(url, header=1,keep_default_na=False) 

tdf = table[0]
tdf.columns = ['PostalCode','Borough','Neighborhood']
tdf.head()

  PostalCode           Borough      Neighborhood
0        M2A      Not assigned      Not assigned
1        M3A        North York         Parkwoods
2        M4A        North York  Victoria Village
3        M5A  Downtown Toronto      Harbourfront
4        M5A  Downtown Toronto       Regent Park

In [25]:
tdf1 = tdf.query('Borough != "Not assigned"').reset_index(drop=True)
tdf1.head()

  PostalCode           Borough      Neighborhood
0        M3A        North York         Parkwoods
1        M4A        North York  Victoria Village
2        M5A  Downtown Toronto      Harbourfront
3        M5A  Downtown Toronto       Regent Park
4        M6A        North York  Lawrence Heights

In [26]:
tdf2=tdf1.groupby('PostalCode', as_index=False).agg(lambda x: ', '.join(set(x.dropna())))
tdf2.head()

  PostalCode      Borough                            Neighborhood
0        M1B  Scarborough                          Malvern, Rouge
1        M1C  Scarborough  Highland Creek, Port Union, Rouge Hill
2        M1E  Scarborough       Guildwood, West Hill, Morningside
3        M1G  Scarborough                                  Woburn
4        M1H  Scarborough                               Cedarbrae

In [12]:
tdf2.loc[tdf2['Neighborhood'] == 'Not assigned', 'Neighborhood' ] = tdf2['Borough']
tdf2.head(12)

   PostalCode      Borough                                       Neighborhood
0         M1B  Scarborough                                     Malvern, Rouge
1         M1C  Scarborough             Highland Creek, Port Union, Rouge Hill
2         M1E  Scarborough                  Guildwood, West Hill, Morningside
3         M1G  Scarborough                                             Woburn
4         M1H  Scarborough                                          Cedarbrae
5         M1J  Scarborough                                Scarborough Village
6         M1K  Scarborough        Kennedy Park, East Birchmount Park, Ionview
7         M1L  Scarborough                    Golden Mile, Oakridge, Clairlea
8         M1M  Scarborough    Scarborough Village West, Cliffside, Cliffcrest
9         M1N  Scarborough                        Cliffside West, Birch Cliff
10        M1P  Scarborough  Wexford Heights, Dorset Park, Scarborough Town...
11        M1R  Scarborough                                  Wexford, Maryvale

In [13]:
tdf2.shape[0]

103